on:
  schedule:
    - cron: '0 14 * * *'
  workflow_dispatch:

jobs:
  import-data:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::tidyverse 
            any::rebird
            any::hms
            any::jsonlite
        env:
          EBIRD_KEY: ${{ secrets.EBIRD_KEY }}

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Import data
        env:
          EBIRD_KEY: ${{ secrets.EBIRD_KEY }}
        run: Rscript -e 'source("scripts/02_Past_Week.R")'

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add data/cleaned_data/checklists.json
          git add docs/graphics/frequency_plot.jpg
          git commit -m 'Data updated' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
